python tools/train.py configs/swin/cascade_mask_rcnn_swin_base_patch4_window7_mstrain_480-800_giou_4conv1f_adamw_3x_voc_shipdet_dcic_2.py --resume-from cascade_mask_rcnn_swin_base_patch4_window7.pth

# python tools/train.py configs/swin/cascade_mask_rcnn_swin_base_patch4_window7_mstrain_480-800_giou_4conv1f_adamw_3x_voc_shipdet_dcic.py --resume-from work_dirs/cascade_mask_rcnn_swin_base_patch4_window7_mstrain_480-800_giou_4conv1f_adamw_3x_voc_shipdet_dcic/epoch_7.pth
